# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Topics
    url: topics/
    weight: 10
    identifier: topics
  - name: Organizers
    url: organizers/
    weight: 20
    identifier: organizers
  - name: Invited Speakers
    url: "#speakers"
    weight: 30
  - name: Participants
    url: participants/
    weight: 40
  - name: Venue
    url: "#thevenue"
    weight: 50
  - name: Proceeding
    url: "#proceeding"
    weight: 60
  - name: Travel Resources
    url: travel/
    weight: 70
  - name: Contact
    url: "#contact"
    weight: 80
