# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Rationale
    url: rationale/
    weight: 5
    identifier: rationale
  - name: Poster
    url: poster/
    weight: 7
    identifier: poster
  - name: Topics
    url: topics/
    weight: 10
    identifier: topics
  - name: Program
    url: program/
    weight: 15
    identifier: program
  - name: Organizers
    url: organizers/
    weight: 20
    identifier: organizers
  - name: Invited Speakers
    url: '#speakers'
    weight: 30
    identifier: speakers
  - name: Participants
    url: participants/
    weight: 40
    identifier: participants
  - name: Venue
    url: "#venue"
    weight: 50
    identifier: venue
  - name: Proceedings
    url: "#proceedings"
    weight: 60
    identifier: proceedings
  - name: Travel Information
    url: travel/
    weight: 70
    identifier: travel
  - name: Registration
    url: registration/
    weight: 80
    identifier: registration
  - name: Contact
    url: "#contact"
    weight: 90
    identifier: contact
